### ISSUE TITLE
サーバのストック消化とリファクタリング

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-server#38]
### タスクの候補
- [ ] 適切なレスポンスを返す（Status Code もふくめ）
- [ ] 不適切なコードがないかをチェックし、都度治す
- [ ] go のインデントをスペースからタブに変更 #36
- [ ] エンドポイントの URI を一貫性持たせる #34
- [ ] foreign_key が適切に機能していない可能性がある #22
- [ ] created_at と updated_at を利用できるようにする #20
- [ ] fresh は models の変更を検知してくれない #29
- [ ] playing_stage_id カラムを削除する #21
- [ ] id カラムに uuid 型を使う #19
- [ ] soda migrate を自動化する #18
- [ ] mysqldump を使えるようにする #17
- [ ] docker のタイムゾーン設定 #14
- [ ] 適切なログの出力 #11
